### ISSUE TITLE
A ticket.

### ISSUE THREAD

**Issue by proofit404** [0cry/bfebyncgqax#3]
@0cruft create https://github.com/audreyfeldroy/cookiecutter-pypackage

```yml
full_name: John Doe
email: johndoe@example.com
github_username: johndoe
project_name: My Awesome Python Project
use_pypi_deployment_with_travis: n
```

**Comment by proofit404** [comment]
@0cruft create https://github.com/audreyfeldroy/cookiecutter-pypackage

```yml
full_name: John Doe
email: johndoe@example.com
github_username: johndoe
project_name: My Awesome Python Project
use_pypi_deployment_with_travis: n
```
